### ISSUE TITLE
Audit Album Details Page

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#39]
Check the current implementation of this page: https://projects.invisionapp.com/share/AY6N3DEB5#/screens/145633696

What's done? What remains? Write out tasks in this issue and then methodically work through them.

**Comment by sumeetjain** [comment]
Example:
- [ ] 'Edit Album' needs to appear and should link directly to the admin page for this album (Josh implemented the admin system in #21 )

**Comment by coryj1990** [comment]
Is it safe to say that to complete this issue I need to make sure our /albums/(album id) page has all the same information/functionality as in the invision link?

**Comment by sumeetjain** [comment]
Correct. And, to be clear, the design implementation is _not_ part of it.

**Comment by coryj1990** [comment]
So far my list of things we don't have includes some things outside of just the details page, but the full list looks like:
1. Release date selection needs to include years before 2011 and only include past years.
2. Show photos of Album
3. A link to admin/albums is needed
4. Determine if Invision's "other info" (bottom right area from the link) is the same as group Bio
5. Label/Producer is needed within album creation.
6. Home link needs to be redirected to the root page.

But items 2, 3, and 6 would be things of being fixed just within the album's show controller action and view files whereas the other issues are more related to the process of adding albums. 
Outside of what the scope what I should be auditing, does my list appear complete. I don't think I missed anything.

Edit: Also, should there be band/group names next to every song for an album?

**Comment by sumeetjain** [comment]
Of the list you have, these are tasks related to this issue:
- ~Release date selection needs to include years before 2011 and only include past years.~ (Because it's related to the _form for creating new albums–not the display of an album.)
- [x] Show photos of Album
- [x] A link to admin/albums is needed
- ~Determine if Invision's "other info" (bottom right area from the link) is the same as group Bio
  Label/Producer is needed within album creation.~ (I don't understand this sentence.)
- ~Home link needs to be redirected to the root page.~ (Related to the layout–not to this specific page.)

> Also, should there be band/group names next to every song for an album?

No. That's just a unique facet of the example the designer used. This phase of development is not allowing for "compilation albums".

You can begin working on the valid tasks above. If we come across any more tasks, we'll add them.
