### ISSUE TITLE
Improve appearance of admin-only links throughout the site

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#56]

**Comment by rlyons21** [comment]
There are edit links on the album page, artist page, and musicians page (like so: https://projects.invisionapp.com/share/AY6N3DEB5#/screens/145749101 ). Are all of these links only for admin or will anyone be able to edit artist, album and musician info?

If anyone can edit, should there be different links for if you are an admin or not?

Currently the edit links on all of the pages take you to the admin part of the app.

**Comment by sumeetjain** [comment]
Only admins can edit.
