### ISSUE TITLE
Customize text of Kaminari pagination

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#59]
A gem called Kaminari is being used to generate paginated links for the list of albums. Check out the gem's documentation and see if we can customize the text it adds to the view. Currently it's adding "Displaying X of Y items", but we'd like to manage that ourselves.

**Comment by DiwthL83** [comment]
We can; it would require editing a YAML file in the Rails root directory to change what the default text displays. See below for an excerpt from the Kaminari documentation at http://www.rubydoc.info/gems/kaminari/0.17.0#Paginating_a_generic_Array_object:

<b>I18n and labels</b>
The default labels for 'first', 'last', 'previous', '…' and 'next' are stored in the I18n yaml inside the engine, and rendered through I18n API. You can switch the label value per I18n.locale for your internationalized application. Keys and the default values are the following. You can override them by adding to a YAML file in your <i>Rails.root/config/locales</i> directory."

**Comment by sumeetjain** [comment]
NICE WORK. Solid research skills :)

Can you please check with Rachel/Nikki about what that text should say and make it so?
