### ISSUE TITLE
Document the design system based on the mockups

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#6]
Build a guide to the design system for the site, based on the mockups.
- [x] The design system should be a gallery of components
- [x] The components in the design system should not have any unnecessary layout/position, as that is meant to be added later via layout classes
- [x] Store the component gallery in the application's `/public` directory (for now)

Make sure you follow BEM conventions as strictly as possible (but remember that not everything needs to fit within the block/element structure).

**Comment by nicleemart** [comment]
I'd like for you to look at the components I've created so far. I added comments in my code to explain what certain blocks or elements are and how I plan to use them.

HTML: https://github.com/omahacodeschool/vinyl-archive/blob/component-gallery/public/gallery.html

CSS: https://github.com/omahacodeschool/vinyl-archive/blob/component-gallery/public/style.css

And an afterthought- I don't know if I used the term pagination correctly!

**Comment by sumeetjain** [comment]
- [x] Always use the full HTML5 boilerplate (with the `doctype`, etc).
- [x] `-moz-box-shadow: 0 0 8px #888888;` is in `.album__image` and also `.album__image--small`, which is redundant because any element with `album__image--small` would also have `album__image` (assuming you were following BEM).
- [x] Now that you've gotten started, you're quickly going to have a lot of CSS. Organize it into different files:
  - [x] Utility classes (like `.wrapText`)
  - [x] Components that belong to every page or are otherwise common components (like the header)
  - You might also then find that there are other files you think of later.
- [x] In `.search`, I see `margin-top: 20px;` which should not be a part of the component's inherent design implementation. Remember to use layout classes to achieve positioning.
  - **Maybe** the same can be said of `margin-right: 10px;` in `.album__image--small`, but I'm not sure. Your call. Sometimes margin _is_ inherent to something's design.

In this scenario:

``` html
<div class="wrapText">
            <div class="album__albumName">
                I'm Wide Awake, It's Morning
                </div>
            <div class="album__artistName">
                Bright Eyes
            </div>
        </div>
```

I think this would be better:

``` html
<div class="album__albumName wrapText">
                I'm Wide Awake, It's Morning
                </div>
            <div class="album__artistName wrapText">
                Bright Eyes
            </div>
```

Otherwise it looks like `wrapText` is, in some meaningful way, the **parent** of the album names. It's not though. Apply utility classes to the specific elements they should affect.

**Comment by nicleemart** [comment]
Oh yeah, that's how modifiers work. I remember now!
