### ISSUE TITLE
Get number of albums for fomat links

### ISSUE THREAD

**Issue by rlyons21** [sumeetjain/vinyl-archive#62]
- [x] Display which number of albums being displayed on page.  Example 9 - 16 of 200. 
- [x] Previous and Next Button only clickable when there is content for those pages.

**Comment by NCFindley** [comment]
Add 
 Display which number of albums being displayed on page. Example 9 - 16 of 200.
 Previous and Next Button only clickable when there is content for those pages

to first comment to display on issue page.

**Comment by NCFindley** [comment]
This function is all ready in master by using page_entries_info.
