### ISSUE TITLE
Home page filters don't have a reset

### ISSUE THREAD

**Issue by coryj1990** [sumeetjain/vinyl-archive#85]
Clicking the "The Vinyl Archive" in the header will bring up all the albums just fine, but because there is a section of the page where its responsibility is to apply specific filters one of them should be an "All Cities" and "All Genres" link.
- [ ] Include another link in list of City, Genres, Decades, and Formats that clears any present filter (i.e. just a link to the root)

**Comment by coryj1990** [comment]
Its been a while since I looked at this project, but I could have sworn I saw a link in the list of cities and genres that would show all cities or all genres. Is there a reason why it was removed or why it shouldn't be in this project?

**Comment by rlyons21** [comment]
![screen shot 2016-09-05 at 10 58 49 am](https://cloud.githubusercontent.com/assets/19532771/18253112/d104a5ae-7357-11e6-8dcc-d573b4bf142f.png)

Based on the design comp, it doesn't look like those links are supposed to be there. If they were there previously, then that was why they were removed.
