### ISSUE TITLE
Add an album header link doesn't exist

### ISSUE THREAD

**Issue by coryj1990** [sumeetjain/vinyl-archive#86]
Typing in the extension /albums/new will take me to the form, but the header should take the user there too.
- [x] Make a link for the Add an album inside the header that leads to /albums/new

**Comment by coryj1990** [comment]
I made this issue because I just wanted to click a link to get to /albums/new instead of typing it in, but after adding that link to the form (PR here https://github.com/omahacodeschool/vinyl-archive/pull/89) I looked back at the demo's form and saw it has a different layout with no header and footer. Is there a way to prevent views/albums/new.html.erb from being injected in the yeild of layouts/application to prevent those headers and footers from appearing? Or would it be better to create a new layout file. Would the latter be front end?

**Comment by sumeetjain** [comment]
> Is there a way to prevent views/albums/new.html.erb from being injected in the yeild of layouts/application to prevent those headers and footers from appearing?

Yup! [Instructions.](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rails%20dont%20use%20layout)
